{% set version = "4.0.0" %}
{% set name = "statsd" %}
{% set sha256 = "e767eb2b8c705ca4c0a55b96fe47f80ce15ba98c7a851dd2ad00504d29cb2e3c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - nose
    - python
    - mock
  commands:
    - python -m nose statsd

about:
  home: https://github.com/jsocol/pystatsd
  license: MIT
  summary: A Python client for statsd
  license_file: LICENSE
  doc_url: http://statsd.readthedocs.io
  dev_url: https://github.com/jsocol/pystatsd
  license_family: MIT

extra:
  recipe-maintainers:
    - bollwyvl
